# -*- coding: utf-8 -*-
"""CNN Visualization...aim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXz3CDcxY2dzB2vylJZzRlpwlJxr1kF2
"""

from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np

model = VGG16(weights='imagenet')

model.summary()

from keras.utils import plot_model
plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

for i in range(len(model.layers)):
	# check the convolutional layer
	if 'conv' not in model.layers[i].name:
		continue
	# filter weights
	filters, biases = model.layers[i].get_weights()
	print("layer number",i,model.layers[i].name, filters.shape)

# retriv weight from the second hidden layer
filters, biases = model.layers[1].get_weights()
print(filters.shape)

# normalize  the filter values to 0-1, so we can visual them
f_min,f_max = filters.min(),filters.max()
filters = (filters - f_min)/(f_max - f_min)

import matplotlib.pyplot as pyplot

n_filters =6
ix=1
fig = pyplot.figure(figsize=(15,10))
for i in range(n_filters):
    # get the filters
    f = filters[:,:,:,i]
    for j in range(3):
        # subplot for 6 filters and 3 channels
        pyplot.subplot(n_filters,3,ix)
        pyplot.imshow(f[:,:,j] ,cmap='gray')
        ix+=1
#plot the filters
pyplot.show()

model = Model(inputs=model.inputs , outputs=model.layers[1].output)

from tensorflow.keras.utils import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from numpy import expand_dims

image = load_img("/content/gettyimages-1775109440-612x612.jpg" , target_size=(224,224))

# convert the image to an array
image = img_to_array(image)
# expand dimensions so that it represents a single 'sample'
image = expand_dims(image, axis=0)

image = preprocess_input(image)

#calculating features_map
features = model.predict(image)

fig = pyplot.figure(figsize=(20,15))
for i in range(1,features.shape[3]+1):

    pyplot.subplot(8,8,i)
    pyplot.imshow(features[0,:,:,i-1] , cmap='gray')

pyplot.show()

model2 = VGG16()

layer_index = [ 2, 5 , 9 , 13 , 17]
outputs = [model2.layers[i].output for i in layer_index]

model3 = Model( inputs= model2.inputs, outputs = outputs)

feature_map = model3.predict(image)

for i,fmap in zip(layer_index,feature_map):
    fig = pyplot.figure(figsize=(20,15))
    fig.suptitle("Layer_{}".format(i) , fontsize=20)
    for i in range(1,features.shape[3]+1):

        pyplot.subplot(8,8,i)
        pyplot.imshow(fmap[0,:,:,i-1] , cmap='gray')

pyplot.show()

